use std::io;

use serde_json::Value;

use crate::block_definition::BlockDataset;
use crate::content_reader::ContentModel;

pub const GENERATED_SOURCE_PREFIX: &str = "@assembler:";

#[derive(Debug)]
pub struct GeneratedFile {
    pub relative_path: String,
    pub bytes: Vec<u8>,
}

pub fn generate_site_files(
    content: &ContentModel,
    block_dataset: &BlockDataset,
) -> io::Result<Vec<GeneratedFile>> {
    let mut files = vec![
        value_module("assembled/content/metadata.ts", "metadata", &content.site)?,
        value_module(
            "assembled/content/redirects.ts",
            "redirects",
            &content.redirects,
        )?,
        value_module("assembled/content/gone.ts", "gone", &content.gone)?,
    ];

    let mut page_imports = Vec::new();
    for (index, page) in content.pages.iter().enumerate() {
        let identifier = format!("page{index}");
        let relative_path = format!("assembled/content/pages/page-{index:04}.ts");
        files.push(value_module(&relative_path, &identifier, page)?);
        page_imports.push((identifier, format!("./pages/page-{index:04}")));
    }

    let mut post_imports = Vec::new();
    for (index, post) in content.posts.iter().enumerate() {
        let identifier = format!("post{index}");
        let relative_path = format!("assembled/content/posts/post-{index:04}.ts");
        files.push(value_module(&relative_path, &identifier, post)?);
        post_imports.push((identifier, format!("./posts/post-{index:04}")));
    }

    files.push(GeneratedFile {
        relative_path: "assembled/content/index.ts".to_string(),
        bytes: content_index_source(&page_imports, &post_imports).into_bytes(),
    });
    files.push(GeneratedFile {
        relative_path: "assembled/block-registry.ts".to_string(),
        bytes: block_registry_source(block_dataset).into_bytes(),
    });
    files.push(GeneratedFile {
        relative_path: "assembled/main.tsx".to_string(),
        bytes: client_entry_source().into_bytes(),
    });
    files.push(GeneratedFile {
        relative_path: "assembled/entry-server.tsx".to_string(),
        bytes: server_entry_source().into_bytes(),
    });

    Ok(files)
}

fn value_module(relative_path: &str, identifier: &str, value: &Value) -> io::Result<GeneratedFile> {
    let serialized = serde_json::to_string_pretty(value).map_err(invalid_data)?;
    let serialized = serialized
        .replace('\u{2028}', "\\u2028")
        .replace('\u{2029}', "\\u2029");
    let source = format!(
        "// Generated by bezot_project_assembler. Do not edit.\n\nconst {identifier} = {serialized} as const;\n\nexport default {identifier};\n"
    );

    Ok(GeneratedFile {
        relative_path: relative_path.to_string(),
        bytes: source.into_bytes(),
    })
}

fn content_index_source(
    page_imports: &[(String, String)],
    post_imports: &[(String, String)],
) -> String {
    let mut source = String::from(
        "// Generated by bezot_project_assembler. Do not edit.\n\n\
import type { SiteContent } from '../../src/application/site-contract';\n\
import metadata from './metadata';\n\
import redirects from './redirects';\n\
import gone from './gone';\n",
    );

    for (identifier, module) in page_imports.iter().chain(post_imports) {
        source.push_str(&format!("import {identifier} from '{module}';\n"));
    }

    source.push_str("\nexport const content = {\n");
    source.push_str("  site: metadata,\n  redirects,\n  gone,\n");
    source.push_str(&format!(
        "  pages: [{}],\n",
        page_imports
            .iter()
            .map(|(identifier, _)| identifier.as_str())
            .collect::<Vec<_>>()
            .join(", ")
    ));
    source.push_str(&format!(
        "  posts: [{}],\n",
        post_imports
            .iter()
            .map(|(identifier, _)| identifier.as_str())
            .collect::<Vec<_>>()
            .join(", ")
    ));
    source.push_str("} as const satisfies SiteContent;\n");
    source
}

fn block_registry_source(block_dataset: &BlockDataset) -> String {
    let mut source = String::from(
        "// Generated by bezot_project_assembler. Do not edit.\n\n\
import type { BlockRegistry } from '../src/application/site-contract';\n",
    );

    for definition in block_dataset.blocks.values() {
        source.push_str(&format!(
            "import {{ {} }} from '../src/{}';\n",
            definition.component.export, definition.component.module
        ));
    }

    source.push_str("\nexport const blockRegistry = {\n");
    for (block_name, definition) in &block_dataset.blocks {
        source.push_str(&format!(
            "  {}: {},\n",
            quoted_javascript_string(block_name),
            definition.component.export
        ));
    }
    source.push_str("} satisfies BlockRegistry;\n");
    source
}

fn quoted_javascript_string(value: &str) -> String {
    serde_json::to_string(value).expect("serializing a Rust string cannot fail")
}

fn client_entry_source() -> String {
    String::from(
        "// Generated by bezot_project_assembler. Do not edit.\n\n\
import { StrictMode } from 'react';\n\
import { BrowserRouter } from 'react-router-dom';\n\
import { createRoot, hydrateRoot } from 'react-dom/client';\n\
import { App } from '../src/App';\n\
import { createSiteRuntime } from '../src/application/create-site-runtime';\n\
import '../src/index.css';\n\
import { blockRegistry } from './block-registry';\n\
import { content } from './content';\n\n\
const runtime = createSiteRuntime(content, blockRegistry);\n\
const application = (\n\
  <StrictMode>\n\
    <BrowserRouter>\n\
      <App runtime={runtime} />\n\
    </BrowserRouter>\n\
  </StrictMode>\n\
);\n\n\
const container = document.getElementById('root');\n\n\
if (!container) {\n\
  throw new Error('Application root element is missing');\n\
}\n\n\
if (container.hasChildNodes()) {\n\
  hydrateRoot(container, application);\n\
} else {\n\
  createRoot(container).render(application);\n\
}\n",
    )
}

fn server_entry_source() -> String {
    String::from(
        "// Generated by bezot_project_assembler. Do not edit.\n\n\
import { renderToString } from 'react-dom/server';\n\
import { MemoryRouter } from 'react-router-dom';\n\
import { App } from '../src/App';\n\
import { createSiteRuntime } from '../src/application/create-site-runtime';\n\
import { blockRegistry } from './block-registry';\n\
import { content } from './content';\n\n\
const runtime = createSiteRuntime(content, blockRegistry);\n\n\
export function getPrerenderRoutes() {\n\
  return runtime.getPrerenderRoutes();\n\
}\n\n\
export function getSiteContent() {\n\
  return runtime.content;\n\
}\n\n\
export function render(url: string) {\n\
  const route = runtime.resolveRoute(url);\n\
  const appHtml = renderToString(\n\
    <MemoryRouter initialEntries={[url]}>\n\
      <App runtime={runtime} />\n\
    </MemoryRouter>,\n\
  );\n\n\
  return {\n\
    appHtml,\n\
    seo: route.seo,\n\
    status: route.kind === 'page' || route.kind === 'root' ? 200 : 404,\n\
  };\n\
}\n",
    )
}

fn invalid_data(error: serde_json::Error) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, error)
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use super::*;
    use crate::block_definition::{
        BlockComponent, BlockDataset, BlockDefinition, BlockKnowledge, BlockRules, BlockSource,
        CardinalityRule, FieldRule, FieldValueType, OutputNode, PlacementRule,
    };

    #[test]
    fn generated_content_is_split_into_modules_and_not_one_site_file() {
        let content = ContentModel {
            site: serde_json::json!({
                "name": "Test site",
                "baseUrl": "https://example.com",
                "defaultLocale": "en-us",
                "locales": ["en-us"],
                "defaultOgImage": "/og.png"
            }),
            redirects: serde_json::json!([]),
            gone: serde_json::json!([]),
            pages: vec![serde_json::json!({"id": "home", "locales": {}})],
            posts: vec![serde_json::json!({"id": "hello", "locales": {}})],
        };
        let block_dataset = block_dataset();

        let files = generate_site_files(&content, &block_dataset).unwrap();
        let paths = files
            .iter()
            .map(|file| file.relative_path.as_str())
            .collect::<Vec<_>>();

        assert!(paths.contains(&"assembled/content/metadata.ts"));
        assert!(paths.contains(&"assembled/content/pages/page-0000.ts"));
        assert!(paths.contains(&"assembled/content/posts/post-0000.ts"));
        assert!(paths.contains(&"assembled/block-registry.ts"));
        assert!(paths.contains(&"assembled/main.tsx"));
        assert!(paths.contains(&"assembled/entry-server.tsx"));
        assert!(!paths.iter().any(|path| path.ends_with("site.ts")));
    }

    fn block_dataset() -> BlockDataset {
        let mut blocks = BTreeMap::new();
        blocks.insert(
            "paragraph".to_string(),
            BlockDefinition {
                source: BlockSource::Content,
                component: BlockComponent {
                    module: "blocks/ParagraphBlock".to_string(),
                    export: "ParagraphBlock".to_string(),
                },
                rules: BlockRules {
                    placement: PlacementRule::Anywhere,
                    cardinality: CardinalityRule::Many,
                    fields: BTreeMap::from([(
                        "text".to_string(),
                        FieldRule {
                            value_type: FieldValueType::String,
                            required: true,
                        },
                    )]),
                    output: OutputNode::Element {
                        tag: "p".to_string(),
                        children: Vec::new(),
                    },
                },
                knowledge: BlockKnowledge {
                    purpose: "Display a paragraph.".to_string(),
                    usage: "Use for body copy.".to_string(),
                    good_examples: Vec::new(),
                    bad_uses: Vec::new(),
                },
            },
        );

        BlockDataset { version: 1, blocks }
    }
}
